// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geografia.proto

package com.bryan.grpc;

public final class Geografia {
  private Geografia() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface paisRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:paisRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string nombrePais = 1;</code>
     */
    java.lang.String getNombrePais();
    /**
     * <code>string nombrePais = 1;</code>
     */
    com.google.protobuf.ByteString
        getNombrePaisBytes();
  }
  /**
   * Protobuf type {@code paisRequest}
   */
  public  static final class paisRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:paisRequest)
      paisRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use paisRequest.newBuilder() to construct.
    private paisRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private paisRequest() {
      nombrePais_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private paisRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              nombrePais_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bryan.grpc.Geografia.internal_static_paisRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bryan.grpc.Geografia.internal_static_paisRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bryan.grpc.Geografia.paisRequest.class, com.bryan.grpc.Geografia.paisRequest.Builder.class);
    }

    public static final int NOMBREPAIS_FIELD_NUMBER = 1;
    private volatile java.lang.Object nombrePais_;
    /**
     * <code>string nombrePais = 1;</code>
     */
    public java.lang.String getNombrePais() {
      java.lang.Object ref = nombrePais_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nombrePais_ = s;
        return s;
      }
    }
    /**
     * <code>string nombrePais = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNombrePaisBytes() {
      java.lang.Object ref = nombrePais_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nombrePais_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNombrePaisBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nombrePais_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNombrePaisBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nombrePais_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bryan.grpc.Geografia.paisRequest)) {
        return super.equals(obj);
      }
      com.bryan.grpc.Geografia.paisRequest other = (com.bryan.grpc.Geografia.paisRequest) obj;

      boolean result = true;
      result = result && getNombrePais()
          .equals(other.getNombrePais());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NOMBREPAIS_FIELD_NUMBER;
      hash = (53 * hash) + getNombrePais().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bryan.grpc.Geografia.paisRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bryan.grpc.Geografia.paisRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bryan.grpc.Geografia.paisRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bryan.grpc.Geografia.paisRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bryan.grpc.Geografia.paisRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bryan.grpc.Geografia.paisRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bryan.grpc.Geografia.paisRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bryan.grpc.Geografia.paisRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bryan.grpc.Geografia.paisRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bryan.grpc.Geografia.paisRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bryan.grpc.Geografia.paisRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bryan.grpc.Geografia.paisRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bryan.grpc.Geografia.paisRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code paisRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:paisRequest)
        com.bryan.grpc.Geografia.paisRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bryan.grpc.Geografia.internal_static_paisRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bryan.grpc.Geografia.internal_static_paisRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bryan.grpc.Geografia.paisRequest.class, com.bryan.grpc.Geografia.paisRequest.Builder.class);
      }

      // Construct using com.bryan.grpc.Geografia.paisRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nombrePais_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bryan.grpc.Geografia.internal_static_paisRequest_descriptor;
      }

      @java.lang.Override
      public com.bryan.grpc.Geografia.paisRequest getDefaultInstanceForType() {
        return com.bryan.grpc.Geografia.paisRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.bryan.grpc.Geografia.paisRequest build() {
        com.bryan.grpc.Geografia.paisRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bryan.grpc.Geografia.paisRequest buildPartial() {
        com.bryan.grpc.Geografia.paisRequest result = new com.bryan.grpc.Geografia.paisRequest(this);
        result.nombrePais_ = nombrePais_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bryan.grpc.Geografia.paisRequest) {
          return mergeFrom((com.bryan.grpc.Geografia.paisRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bryan.grpc.Geografia.paisRequest other) {
        if (other == com.bryan.grpc.Geografia.paisRequest.getDefaultInstance()) return this;
        if (!other.getNombrePais().isEmpty()) {
          nombrePais_ = other.nombrePais_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bryan.grpc.Geografia.paisRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bryan.grpc.Geografia.paisRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object nombrePais_ = "";
      /**
       * <code>string nombrePais = 1;</code>
       */
      public java.lang.String getNombrePais() {
        java.lang.Object ref = nombrePais_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nombrePais_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nombrePais = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNombrePaisBytes() {
        java.lang.Object ref = nombrePais_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nombrePais_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nombrePais = 1;</code>
       */
      public Builder setNombrePais(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nombrePais_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nombrePais = 1;</code>
       */
      public Builder clearNombrePais() {
        
        nombrePais_ = getDefaultInstance().getNombrePais();
        onChanged();
        return this;
      }
      /**
       * <code>string nombrePais = 1;</code>
       */
      public Builder setNombrePaisBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nombrePais_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:paisRequest)
    }

    // @@protoc_insertion_point(class_scope:paisRequest)
    private static final com.bryan.grpc.Geografia.paisRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bryan.grpc.Geografia.paisRequest();
    }

    public static com.bryan.grpc.Geografia.paisRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<paisRequest>
        PARSER = new com.google.protobuf.AbstractParser<paisRequest>() {
      @java.lang.Override
      public paisRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new paisRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<paisRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<paisRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bryan.grpc.Geografia.paisRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface capitalResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:capitalResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string nombreCapital = 1;</code>
     */
    java.lang.String getNombreCapital();
    /**
     * <code>string nombreCapital = 1;</code>
     */
    com.google.protobuf.ByteString
        getNombreCapitalBytes();
  }
  /**
   * Protobuf type {@code capitalResponse}
   */
  public  static final class capitalResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:capitalResponse)
      capitalResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use capitalResponse.newBuilder() to construct.
    private capitalResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private capitalResponse() {
      nombreCapital_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private capitalResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              nombreCapital_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bryan.grpc.Geografia.internal_static_capitalResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bryan.grpc.Geografia.internal_static_capitalResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bryan.grpc.Geografia.capitalResponse.class, com.bryan.grpc.Geografia.capitalResponse.Builder.class);
    }

    public static final int NOMBRECAPITAL_FIELD_NUMBER = 1;
    private volatile java.lang.Object nombreCapital_;
    /**
     * <code>string nombreCapital = 1;</code>
     */
    public java.lang.String getNombreCapital() {
      java.lang.Object ref = nombreCapital_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nombreCapital_ = s;
        return s;
      }
    }
    /**
     * <code>string nombreCapital = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNombreCapitalBytes() {
      java.lang.Object ref = nombreCapital_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nombreCapital_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNombreCapitalBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nombreCapital_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNombreCapitalBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nombreCapital_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bryan.grpc.Geografia.capitalResponse)) {
        return super.equals(obj);
      }
      com.bryan.grpc.Geografia.capitalResponse other = (com.bryan.grpc.Geografia.capitalResponse) obj;

      boolean result = true;
      result = result && getNombreCapital()
          .equals(other.getNombreCapital());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NOMBRECAPITAL_FIELD_NUMBER;
      hash = (53 * hash) + getNombreCapital().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bryan.grpc.Geografia.capitalResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bryan.grpc.Geografia.capitalResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bryan.grpc.Geografia.capitalResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bryan.grpc.Geografia.capitalResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bryan.grpc.Geografia.capitalResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bryan.grpc.Geografia.capitalResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bryan.grpc.Geografia.capitalResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bryan.grpc.Geografia.capitalResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bryan.grpc.Geografia.capitalResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bryan.grpc.Geografia.capitalResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bryan.grpc.Geografia.capitalResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bryan.grpc.Geografia.capitalResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bryan.grpc.Geografia.capitalResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code capitalResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:capitalResponse)
        com.bryan.grpc.Geografia.capitalResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bryan.grpc.Geografia.internal_static_capitalResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bryan.grpc.Geografia.internal_static_capitalResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bryan.grpc.Geografia.capitalResponse.class, com.bryan.grpc.Geografia.capitalResponse.Builder.class);
      }

      // Construct using com.bryan.grpc.Geografia.capitalResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nombreCapital_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bryan.grpc.Geografia.internal_static_capitalResponse_descriptor;
      }

      @java.lang.Override
      public com.bryan.grpc.Geografia.capitalResponse getDefaultInstanceForType() {
        return com.bryan.grpc.Geografia.capitalResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.bryan.grpc.Geografia.capitalResponse build() {
        com.bryan.grpc.Geografia.capitalResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bryan.grpc.Geografia.capitalResponse buildPartial() {
        com.bryan.grpc.Geografia.capitalResponse result = new com.bryan.grpc.Geografia.capitalResponse(this);
        result.nombreCapital_ = nombreCapital_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bryan.grpc.Geografia.capitalResponse) {
          return mergeFrom((com.bryan.grpc.Geografia.capitalResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bryan.grpc.Geografia.capitalResponse other) {
        if (other == com.bryan.grpc.Geografia.capitalResponse.getDefaultInstance()) return this;
        if (!other.getNombreCapital().isEmpty()) {
          nombreCapital_ = other.nombreCapital_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bryan.grpc.Geografia.capitalResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bryan.grpc.Geografia.capitalResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object nombreCapital_ = "";
      /**
       * <code>string nombreCapital = 1;</code>
       */
      public java.lang.String getNombreCapital() {
        java.lang.Object ref = nombreCapital_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nombreCapital_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nombreCapital = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNombreCapitalBytes() {
        java.lang.Object ref = nombreCapital_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nombreCapital_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nombreCapital = 1;</code>
       */
      public Builder setNombreCapital(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nombreCapital_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nombreCapital = 1;</code>
       */
      public Builder clearNombreCapital() {
        
        nombreCapital_ = getDefaultInstance().getNombreCapital();
        onChanged();
        return this;
      }
      /**
       * <code>string nombreCapital = 1;</code>
       */
      public Builder setNombreCapitalBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nombreCapital_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:capitalResponse)
    }

    // @@protoc_insertion_point(class_scope:capitalResponse)
    private static final com.bryan.grpc.Geografia.capitalResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bryan.grpc.Geografia.capitalResponse();
    }

    public static com.bryan.grpc.Geografia.capitalResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<capitalResponse>
        PARSER = new com.google.protobuf.AbstractParser<capitalResponse>() {
      @java.lang.Override
      public capitalResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new capitalResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<capitalResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<capitalResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bryan.grpc.Geografia.capitalResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ciudadResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ciudadResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string nombreCiudad = 1;</code>
     */
    java.lang.String getNombreCiudad();
    /**
     * <code>string nombreCiudad = 1;</code>
     */
    com.google.protobuf.ByteString
        getNombreCiudadBytes();
  }
  /**
   * Protobuf type {@code ciudadResponse}
   */
  public  static final class ciudadResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ciudadResponse)
      ciudadResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ciudadResponse.newBuilder() to construct.
    private ciudadResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ciudadResponse() {
      nombreCiudad_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ciudadResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              nombreCiudad_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bryan.grpc.Geografia.internal_static_ciudadResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bryan.grpc.Geografia.internal_static_ciudadResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bryan.grpc.Geografia.ciudadResponse.class, com.bryan.grpc.Geografia.ciudadResponse.Builder.class);
    }

    public static final int NOMBRECIUDAD_FIELD_NUMBER = 1;
    private volatile java.lang.Object nombreCiudad_;
    /**
     * <code>string nombreCiudad = 1;</code>
     */
    public java.lang.String getNombreCiudad() {
      java.lang.Object ref = nombreCiudad_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nombreCiudad_ = s;
        return s;
      }
    }
    /**
     * <code>string nombreCiudad = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNombreCiudadBytes() {
      java.lang.Object ref = nombreCiudad_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nombreCiudad_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNombreCiudadBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nombreCiudad_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNombreCiudadBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nombreCiudad_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bryan.grpc.Geografia.ciudadResponse)) {
        return super.equals(obj);
      }
      com.bryan.grpc.Geografia.ciudadResponse other = (com.bryan.grpc.Geografia.ciudadResponse) obj;

      boolean result = true;
      result = result && getNombreCiudad()
          .equals(other.getNombreCiudad());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NOMBRECIUDAD_FIELD_NUMBER;
      hash = (53 * hash) + getNombreCiudad().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bryan.grpc.Geografia.ciudadResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bryan.grpc.Geografia.ciudadResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bryan.grpc.Geografia.ciudadResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bryan.grpc.Geografia.ciudadResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bryan.grpc.Geografia.ciudadResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bryan.grpc.Geografia.ciudadResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bryan.grpc.Geografia.ciudadResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bryan.grpc.Geografia.ciudadResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bryan.grpc.Geografia.ciudadResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bryan.grpc.Geografia.ciudadResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bryan.grpc.Geografia.ciudadResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bryan.grpc.Geografia.ciudadResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bryan.grpc.Geografia.ciudadResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ciudadResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ciudadResponse)
        com.bryan.grpc.Geografia.ciudadResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bryan.grpc.Geografia.internal_static_ciudadResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bryan.grpc.Geografia.internal_static_ciudadResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bryan.grpc.Geografia.ciudadResponse.class, com.bryan.grpc.Geografia.ciudadResponse.Builder.class);
      }

      // Construct using com.bryan.grpc.Geografia.ciudadResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nombreCiudad_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bryan.grpc.Geografia.internal_static_ciudadResponse_descriptor;
      }

      @java.lang.Override
      public com.bryan.grpc.Geografia.ciudadResponse getDefaultInstanceForType() {
        return com.bryan.grpc.Geografia.ciudadResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.bryan.grpc.Geografia.ciudadResponse build() {
        com.bryan.grpc.Geografia.ciudadResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bryan.grpc.Geografia.ciudadResponse buildPartial() {
        com.bryan.grpc.Geografia.ciudadResponse result = new com.bryan.grpc.Geografia.ciudadResponse(this);
        result.nombreCiudad_ = nombreCiudad_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bryan.grpc.Geografia.ciudadResponse) {
          return mergeFrom((com.bryan.grpc.Geografia.ciudadResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bryan.grpc.Geografia.ciudadResponse other) {
        if (other == com.bryan.grpc.Geografia.ciudadResponse.getDefaultInstance()) return this;
        if (!other.getNombreCiudad().isEmpty()) {
          nombreCiudad_ = other.nombreCiudad_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bryan.grpc.Geografia.ciudadResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bryan.grpc.Geografia.ciudadResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object nombreCiudad_ = "";
      /**
       * <code>string nombreCiudad = 1;</code>
       */
      public java.lang.String getNombreCiudad() {
        java.lang.Object ref = nombreCiudad_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nombreCiudad_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nombreCiudad = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNombreCiudadBytes() {
        java.lang.Object ref = nombreCiudad_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nombreCiudad_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nombreCiudad = 1;</code>
       */
      public Builder setNombreCiudad(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nombreCiudad_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nombreCiudad = 1;</code>
       */
      public Builder clearNombreCiudad() {
        
        nombreCiudad_ = getDefaultInstance().getNombreCiudad();
        onChanged();
        return this;
      }
      /**
       * <code>string nombreCiudad = 1;</code>
       */
      public Builder setNombreCiudadBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nombreCiudad_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ciudadResponse)
    }

    // @@protoc_insertion_point(class_scope:ciudadResponse)
    private static final com.bryan.grpc.Geografia.ciudadResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bryan.grpc.Geografia.ciudadResponse();
    }

    public static com.bryan.grpc.Geografia.ciudadResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ciudadResponse>
        PARSER = new com.google.protobuf.AbstractParser<ciudadResponse>() {
      @java.lang.Override
      public ciudadResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ciudadResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ciudadResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ciudadResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bryan.grpc.Geografia.ciudadResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface habitantesResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:habitantesResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 habitantes = 1;</code>
     */
    int getHabitantes();
  }
  /**
   * Protobuf type {@code habitantesResponse}
   */
  public  static final class habitantesResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:habitantesResponse)
      habitantesResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use habitantesResponse.newBuilder() to construct.
    private habitantesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private habitantesResponse() {
      habitantes_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private habitantesResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              habitantes_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bryan.grpc.Geografia.internal_static_habitantesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bryan.grpc.Geografia.internal_static_habitantesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bryan.grpc.Geografia.habitantesResponse.class, com.bryan.grpc.Geografia.habitantesResponse.Builder.class);
    }

    public static final int HABITANTES_FIELD_NUMBER = 1;
    private int habitantes_;
    /**
     * <code>int32 habitantes = 1;</code>
     */
    public int getHabitantes() {
      return habitantes_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (habitantes_ != 0) {
        output.writeInt32(1, habitantes_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (habitantes_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, habitantes_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bryan.grpc.Geografia.habitantesResponse)) {
        return super.equals(obj);
      }
      com.bryan.grpc.Geografia.habitantesResponse other = (com.bryan.grpc.Geografia.habitantesResponse) obj;

      boolean result = true;
      result = result && (getHabitantes()
          == other.getHabitantes());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HABITANTES_FIELD_NUMBER;
      hash = (53 * hash) + getHabitantes();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bryan.grpc.Geografia.habitantesResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bryan.grpc.Geografia.habitantesResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bryan.grpc.Geografia.habitantesResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bryan.grpc.Geografia.habitantesResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bryan.grpc.Geografia.habitantesResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bryan.grpc.Geografia.habitantesResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bryan.grpc.Geografia.habitantesResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bryan.grpc.Geografia.habitantesResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bryan.grpc.Geografia.habitantesResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bryan.grpc.Geografia.habitantesResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bryan.grpc.Geografia.habitantesResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bryan.grpc.Geografia.habitantesResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bryan.grpc.Geografia.habitantesResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code habitantesResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:habitantesResponse)
        com.bryan.grpc.Geografia.habitantesResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bryan.grpc.Geografia.internal_static_habitantesResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bryan.grpc.Geografia.internal_static_habitantesResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bryan.grpc.Geografia.habitantesResponse.class, com.bryan.grpc.Geografia.habitantesResponse.Builder.class);
      }

      // Construct using com.bryan.grpc.Geografia.habitantesResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        habitantes_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bryan.grpc.Geografia.internal_static_habitantesResponse_descriptor;
      }

      @java.lang.Override
      public com.bryan.grpc.Geografia.habitantesResponse getDefaultInstanceForType() {
        return com.bryan.grpc.Geografia.habitantesResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.bryan.grpc.Geografia.habitantesResponse build() {
        com.bryan.grpc.Geografia.habitantesResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bryan.grpc.Geografia.habitantesResponse buildPartial() {
        com.bryan.grpc.Geografia.habitantesResponse result = new com.bryan.grpc.Geografia.habitantesResponse(this);
        result.habitantes_ = habitantes_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bryan.grpc.Geografia.habitantesResponse) {
          return mergeFrom((com.bryan.grpc.Geografia.habitantesResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bryan.grpc.Geografia.habitantesResponse other) {
        if (other == com.bryan.grpc.Geografia.habitantesResponse.getDefaultInstance()) return this;
        if (other.getHabitantes() != 0) {
          setHabitantes(other.getHabitantes());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bryan.grpc.Geografia.habitantesResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bryan.grpc.Geografia.habitantesResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int habitantes_ ;
      /**
       * <code>int32 habitantes = 1;</code>
       */
      public int getHabitantes() {
        return habitantes_;
      }
      /**
       * <code>int32 habitantes = 1;</code>
       */
      public Builder setHabitantes(int value) {
        
        habitantes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 habitantes = 1;</code>
       */
      public Builder clearHabitantes() {
        
        habitantes_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:habitantesResponse)
    }

    // @@protoc_insertion_point(class_scope:habitantesResponse)
    private static final com.bryan.grpc.Geografia.habitantesResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bryan.grpc.Geografia.habitantesResponse();
    }

    public static com.bryan.grpc.Geografia.habitantesResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<habitantesResponse>
        PARSER = new com.google.protobuf.AbstractParser<habitantesResponse>() {
      @java.lang.Override
      public habitantesResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new habitantesResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<habitantesResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<habitantesResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bryan.grpc.Geografia.habitantesResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_paisRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_paisRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_capitalResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_capitalResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ciudadResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ciudadResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_habitantesResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_habitantesResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017geografia.proto\"!\n\013paisRequest\022\022\n\nnomb" +
      "rePais\030\001 \001(\t\"(\n\017capitalResponse\022\025\n\rnombr" +
      "eCapital\030\001 \001(\t\"&\n\016ciudadResponse\022\024\n\014nomb" +
      "reCiudad\030\001 \001(\t\"(\n\022habitantesResponse\022\022\n\n" +
      "habitantes\030\001 \001(\0052\347\001\n\006Paises\022.\n\ngetCapita" +
      "l\022\014.paisRequest\032\020.capitalResponse\"\000\0220\n\013g" +
      "etCiudades\022\014.paisRequest\032\017.ciudadRespons" +
      "e\"\0000\001\022>\n\025getCantidadHabitantes\022\014.paisReq" +
      "uest\032\023.habitantesResponse\"\000(\001\022;\n\023getMult" +
      "iplesCapital\022\014.paisRequest\032\020.capitalResp" +
      "onse\"\000(\0010\001B\020\n\016com.bryan.grpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_paisRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_paisRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_paisRequest_descriptor,
        new java.lang.String[] { "NombrePais", });
    internal_static_capitalResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_capitalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_capitalResponse_descriptor,
        new java.lang.String[] { "NombreCapital", });
    internal_static_ciudadResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ciudadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ciudadResponse_descriptor,
        new java.lang.String[] { "NombreCiudad", });
    internal_static_habitantesResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_habitantesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_habitantesResponse_descriptor,
        new java.lang.String[] { "Habitantes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
